apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: templates.kubevirt.io
  annotations:
    description: "OCP kubevirttemplate"
    tags: "kubevirt,ocp,template"
  labels:
    miq.github.io/kubevirt-is-vm-template: "true"
spec:
  group: kubevirt.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Template
    listKind: TemplateList
    singular: template
    plural: templates
    shortNames:
    - template
    - templates
