apiVersion: v1
kind: Template
metadata:
  name: linux-vm-template
  annotations:
    description: "OCP kubevirt linux, template"
    tags: "kubevirt,ocp,template,linux"
  labels:
    miq.github.io/kubevirt-os: rhel-7
    miq.github.io/kubevirt-is-vm-template: true
objects:
- apiVersion: kubevirt.io/v1alpha1
  kind: OfflineVirtualMachine
  metadata:
    name: ${NAME}
  spec:
    template:
      spec:
        domain:
          cpu:
            cores: ${CPU_CORES}
          resources:
            requests:
              memory: ${MEMORY}
          machine:
            type: q35
          devices:
            disks:
              - name: disk0
                volumeName: disk0-pvc
        volumes:
          - name: disk0-pvc
            persistentVolumeClaim:
              claimName: linux-vm-pvc-${NAME}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: linux-vm-pvc-${NAME}
    #FIXME: add an annotation to specify which volume this pvc should be based on
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
parameters:
- description: Name for the new VM
  name: NAME
- name: MEMORY
  description: Amount of memory
  value: 4096Mi
- name: CPU_CORES
  description: Amount of cores
  value: 4
