apiVersion: apiextensions.k8s.io/v1beta1
kind: Template
metadata:
  name: working
  annotations:
    description: "OCP kubevirt linux, template"
    tags: "kubevirt,ocp,template,linux"
  labels:
    miq.github.io/kubevirt-is-vm-template: true
    miq.github.io/kubevirt-os: rhel-7
objects:
- apiVersion: kubevirt.io/v1alpha1
  kind: OfflineVirtualMachine
  metadata:
    name: ${NAME}
  spec:
    template:
      spec:
        domain:
          cpu:
            cores: ${CPU_CORES}
          resources:
            requests:
              memory: ${MEMORY}
          machine:
            type: q35
          devices:
            disks:
            - name: registrydisk
              volumeName: registryvolume
              disk:
                dev: vda
            - name: cloudinitdisk
              volumeName: cloudinitvolume
              disk:
                dev: vdb
        volumes:
          - name: registryvolume
            registryDisk:
              image: kubevirt/fedora-cloud-registry-disk-demo:latest
          - name: cloudinitvolume
            cloudInitNoCloud:
              userDataBase64: I2Nsb3VkLWNvbmZpZwpwYXNzd29yZDogYXRvbWljCnNzaF9wd2F1dGg6IFRydWUKY2hwYXNzd2Q6IHsgZXhwaXJlOiBGYWxzZSB9Cg==
parameters:
- name: NAME
  description: Name for the new VM
- name: MEMORY
  description: Amount of memory in MB
  value: 512Mi
- name: CPU_CORES
  description: Amount of cores
  value: 4
